/** Marketing & Content Agent tool definitions */
import type { ToolDefinition } from "../../types.js";

export const marketingContentTools: ToolDefinition[] = [
  { name: "generate_listing_description", description: "Generate listing description for MLS, Craigslist, social, etc.", parameters: { type: "object", properties: { propertyData: { type: "object" }, platform: { type: "string", description: "mls|craigslist|zillow|instagram|facebook|email" }, stylePreferences: { type: "object" } }, required: ["propertyData", "platform"] } },
  { name: "generate_social_post", description: "Generate social media post (Just Listed, Open House, Just Sold, etc.)", parameters: { type: "object", properties: { postType: { type: "string" }, propertyData: { type: "object" }, branding: { type: "object" }, platform: { type: "string" } }, required: ["postType", "propertyData"] } },
  { name: "generate_flyer", description: "Generate printable property flyer", parameters: { type: "object", properties: { propertyData: { type: "object" }, branding: { type: "object" }, templateStyle: { type: "string" } }, required: ["propertyData"] } },
  { name: "generate_qr_signin", description: "Generate QR code sign-in for open house", parameters: { type: "object", properties: { openHouseId: { type: "string" }, propertyAddress: { type: "string" } }, required: ["openHouseId", "propertyAddress"] } },
  { name: "generate_followup_emails", description: "Generate personalized follow-up emails for open house attendees", parameters: { type: "object", properties: { attendeeList: { type: "array", items: { type: "object" } }, propertyData: { type: "object" }, agentBranding: { type: "object" } }, required: ["attendeeList", "propertyData"] } },
  { name: "generate_daily_digest", description: "Generate daily hot sheet / market digest email", parameters: { type: "object", properties: { farmAreas: { type: "array", items: { type: "string" } }, criteria: { type: "object" }, branding: { type: "object" } }, required: ["farmAreas"] } },
  { name: "generate_offer_comparison", description: "Generate offer comparison matrix for sellers with multiple offers", parameters: { type: "object", properties: { offers: { type: "array", items: { type: "object" } }, scoringWeights: { type: "object" } }, required: ["offers"] } },
  { name: "apply_branding", description: "Apply agent branding (logo, colors, headshot, contact) to content", parameters: { type: "object", properties: { content: { type: "string" }, branding: { type: "object" } }, required: ["content", "branding"] } },
];