import React from 'react';

function App() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>React Web App</h1>
      <p>Generated by Tekton Forge. Start building!</p>
    </div>
  );
}

export default App;