export const DEFAULT_CONFIG = {
  identity: {
    soul: "Tekton Agent — adaptive coding agent that learns",
    name: "tekton",
    soulPath: "~/.tekton/SOUL.md",
    memoryPath: "~/.tekton/MEMORY.md",
    userModelPath: "~/.tekton/USER.md",
    maxMemoryChars: 4000,
    maxUserModelChars: 2000,
    maxContextChars: 2000,
  },
  models: {
    fast: {
      model: "gemma4:e4b",
      provider: "ollama",
    },
    deep: {
      model: "gemma4:26b",
      provider: "ollama",
    },
    fallbackChain: [] as Array<{ model: string; provider: string }>,
  },
  routing: {
    mode: "auto" as const,
    complexityThreshold: 0.6,
    simpleThreshold: 0.3,
    escalationKeywords: [] as string[],
    simpleKeywords: [] as string[],
  },
  compression: {
    enabled: true,
    defaultTier: "full" as const,
  },
  learning: {
    enabled: true,
    autoExtract: true,
    complexityThreshold: 0.7,
  },
  contextHygiene: {
    maxTurns: 50,
    compactPercent: 0.75,
    pruneAfter: 30,
  },
  telemetry: {
    enabled: true,
    dbPath: "~/.tekton/telemetry.db",
  },
  budget: {
    dailyLimit: null as number | null,
    sessionLimit: null as number | null,
    warnPercent: 80,
  },
  dashboard: {
    port: 7890,
    autoStart: false,
    host: "127.0.0.1",
    refreshIntervalMs: 5000,
  },
  gateway: {
    platforms: [] as string[],
    tokens: {} as Record<string, string>,
  },
  voice: {
    stt: "local",
    tts: "edge",
    providers: {} as Record<string, string>,
    recordKey: "ctrl+b",
    maxRecordingSeconds: 120,
    autoTTS: false,
    silenceThreshold: 200,
    silenceDuration: 3.0,
    gatewayVoice: false,
  },
  terminal: {
    backend: "local",
    cwd: "",
    timeout: 30000,
  },
  skills: {
    dirs: [] as string[],
    externalDirs: [] as string[],
  },
  docling: {
    enabled: true as boolean,
    mode: "http" as const,
    port: 7701,
  },
  agents: {
    maxAgents: 4,
    idleTimeoutMs: 60000,
    taskTimeoutMs: 120000,
    concurrencyLimit: 4,
  },
  sound: {
    enabled: true as boolean,
  },
  memory: {
    provider: "sqlite",
    path: "~/.tekton/memory.db",
  },
  forge: {
    enabled: false as boolean,
    projectsDir: "~/.tekton/forge-projects",
    maxConcurrentAgents: 4,
    defaultSessionLimit: 20,
    scribeModel: "gemini-flash",
  },
  contextEngineer: {
    enabled: true as boolean,
    model: "gemini-flash",
    rawWindowSize: 12,
    rewriteInterval: 10,
    maxPrecisionLogTokens: 2000,
    maxRollingContextTokens: 3000,
    fallbackToCompression: "caveman-compact",  // used when CE disabled
  },
  knowledge: {
    enabled: false as boolean,
    storePath: "~/.tekton/knowledge/",
    indexPath: "~/.tekton/knowledge/index/",
    autoInject: true as boolean,
    maxInjectTokens: 1500,
    maxInjectChunks: 3,
    embeddingModel: "text-embedding-3-small",
    topics: {} as Record<string, string[]>,
  },
  fusion: {
    enabled: true as boolean,
    mode: "parallel" as const,
    models: [
      { model: "kwangsuklee/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:latest", provider: "ollama", weight: 1.0, role: "primary" as const, active: true },
      { model: "glm-5.1:cloud", provider: "ollama", weight: 0.9, role: "primary" as const, active: true },
      { model: "deepseek-r1:32b", provider: "ollama", weight: 0.85, role: "secondary" as const, active: true },
      { model: "kimi-k2.5:cloud", provider: "ollama", weight: 0.8, role: "secondary" as const, active: true },
      { model: "gemma4:e4b", provider: "ollama", weight: 0.75, role: "specialist" as const, active: true },
      { model: "nemotron-3-super:cloud", provider: "ollama", weight: 0.8, role: "secondary" as const, active: true },
      { model: "minimax-m3:cloud", provider: "ollama", weight: 0.75, role: "specialist" as const, active: true },
      { model: "glm-5.2:cloud", provider: "ollama", weight: 0.85, role: "secondary" as const, active: true },
    ],
    maxConcurrent: 3,
    timeoutMs: 120000,
    minModels: 2,
    useOpenRouterPlugin: false as boolean,
    qualityThreshold: 0.85,
    autoSelect: true as boolean,
    trackEffectiveness: true as boolean,
    maxExtraCost: 0,
    useJudge: true as boolean,
    judgeModel: "gemma4:e4b",
    uncensoredMode: false as boolean,
  },
  session: {
    contextMode: "context-engineer" as const,
  },
};