/**
 * Voice Types — STT, TTS, recording, and gateway voice configurations.
 */
export const DEFAULT_VOICE_CONFIG = {
    enabled: false,
    autoTTS: false,
    recordKey: "ctrl+b",
    maxRecordingSeconds: 120,
    silenceThreshold: 200,
    silenceDuration: 3.0,
    sttFallbackChain: ["local", "groq", "openai"],
    gatewayVoice: false,
    discordAutoJoin: false,
};
// ── Whisper Hallucination Filter ─────────────────────────────────────
/** Known phantom phrases produced by Whisper hallucinations */
export const WHISPER_HALLUCINATIONS = [
    "Thank you for watching.",
    "Thank you for watching this video.",
    "Subscribe to my channel.",
    "Please subscribe.",
    "Like and subscribe.",
    "Thank you.",
    "Thanks for watching.",
    " Bye.",
    " By.",
    "Hello.",
    "Hello, welcome to the channel.",
    "Welcome to the channel.",
    "Welcome to the video.",
    "Okay.",
    "OK.",
    "Mm-hmm.",
    "Mm hmm.",
    "Uh-huh.",
    "Uh huh.",
    "Hmm.",
    "Huh.",
    "Yeah.",
    "You know.",
    "I'm sorry.",
    "I'm sorry, I'm sorry.",
    "So.",
    "",
    " ",
    "  ",
    "The.",
    "And.",
    "You.",
    "It.",
    "Is.",
    "This is a test.",
    "This is a recording.",
    "Testing, testing.",
    "Testing 1, 2, 3.",
    "Can you hear me?",
    "One, two, three.",
    " 1, 2, 3.",
    "Am I on?",
    "Is this on?",
    "Hello? Hello?",
    "Okay, okay.",
    "Right.",
    "Sure.",
    "Yeah, yeah.",
    "Mhm.",
];
//# sourceMappingURL=types.js.map