/**
 * Python Template Scripts — Training scripts built as line arrays.
 * These are NOT executed directly — they are rendered with config values
 * and written to disk for the user to run.
 */

function buildScript(lines: string[]): string {
  return lines.join("\n");
}

function v(value: string | number | boolean): string {
  return String(value);
}

// ── QLoRA with Unsloth ────────────────────────────────────────────────

export function generateQLoRAScript(config: {
  baseModel: string; outputDir: string; dataset: string; epochs: number;
  batchSize: number; gradientAccumulationSteps: number; learningRate: number;
  maxSeqLength: number; loraRank: number; loraAlpha: number; loraDropout: number;
  saveSteps: number; evalSteps: number; loggingSteps: number;
  useUnsloth: boolean; useFlashAttention: boolean; precision: string;
  seed: number; outputName: string;
}): string {
  return buildScript([
    '#!/usr/bin/env python3',
    '"""',
    `Tekton QLoRA Fine-Tuning Script`,
    `Model: ${config.baseModel}`,
    `Method: QLoRA (${config.useUnsloth ? "Unsloth" : "Standard"})`,
    'Generated by Tekton ML-Ops',
    '"""',
    '',
    config.useUnsloth ? 'from unsloth import FastLanguageModel' : '# Unsloth not used',
    'import torch',
    'from trl import SFTTrainer',
    'from transformers import TrainingArguments',
    'from datasets import load_dataset',
    '',
    '# Configuration',
    `MODEL_NAME = "${config.baseModel}"`,
    `OUTPUT_DIR = "${config.outputDir}/${config.outputName}"`,
    `DATASET = "${config.dataset}"`,
    `MAX_SEQ_LENGTH = ${config.maxSeqLength}`,
    `LORA_RANK = ${config.loraRank}`,
    `LORA_ALPHA = ${config.loraAlpha}`,
    `LORA_DROPOUT = ${config.loraDropout}`,
    `SEED = ${config.seed}`,
    '',
    '# Load Model & Tokenizer',
    config.useUnsloth ? 'model, tokenizer = FastLanguageModel.from_pretrained(' : 'model = AutoModelForCausalLM.from_pretrained(',
    `    model_name=MODEL_NAME,`,
    `    max_seq_length=MAX_SEQ_LENGTH,`,
    `    dtype=None,`,
    `    load_in_4bit=True,`,
    ')',
    '',
    config.useUnsloth ? '# Apply LoRA Adapters' : '',
    config.useUnsloth ? 'model = FastLanguageModel.get_peft_model(' : '# Apply LoRA via PEFT',
    config.useUnsloth ? '    model,' : '',
    config.useUnsloth ? `    r=LORA_RANK,` : '',
    config.useUnsloth ? `    lora_alpha=LORA_ALPHA,` : '',
    config.useUnsloth ? `    lora_dropout=LORA_DROPOUT,` : '',
    config.useUnsloth ? '    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],' : '',
    config.useUnsloth ? '    bias="none",' : '',
    config.useUnsloth ? '    use_gradient_checkpointing="unsloth",' : '',
    config.useUnsloth ? '    random_state=SEED,' : '',
    config.useUnsloth ? ')' : '',
    '',
    '# Load Dataset',
    'dataset = load_dataset(DATASET, split="train")',
    '',
    'def formatting_func(examples):',
    '    inputs = examples.get("instruction", examples.get("input", ""))',
    '    outputs = examples.get("output", examples.get("response", ""))',
    '    texts = [f"### Instruction:\\n{i}\\n\\n### Response:\\n{o}" for i, o in zip(inputs, outputs)]',
    '    return {"text": texts}',
    '',
    'dataset = dataset.map(formatting_func, batched=True)',
    '',
    '# Training Arguments',
    `training_args = TrainingArguments(`,
    `    output_dir=OUTPUT_DIR,`,
    `    num_train_epochs=${config.epochs},`,
    `    per_device_train_batch_size=${config.batchSize},`,
    `    gradient_accumulation_steps=${config.gradientAccumulationSteps},`,
    `    learning_rate=${config.learningRate},`,
    `    weight_decay=0.01,`,
    `    warmup_steps=${Math.floor(config.saveSteps / 2)},`,
    `    logging_steps=${config.loggingSteps},`,
    `    save_steps=${config.saveSteps},`,
    `    eval_steps=${config.evalSteps},`,
    `    save_total_limit=3,`,
    config.precision === "bf16" ? "    bf16=True," : config.precision === "fp16" ? "    fp16=True," : "",
    '    optim="adamw_8bit",',
    '    seed=SEED,',
    '    report_to="none",',
    ')',
    '',
    '# Train',
    'trainer = SFTTrainer(',
    '    model=model,',
    ...(config.useUnsloth ? ['    tokenizer=tokenizer,'] : []),
    '    train_dataset=dataset,',
    '    dataset_text_field="text",',
    '    max_seq_length=MAX_SEQ_LENGTH,',
    '    args=training_args,',
    ')',
    '',
    'trainer.train()',
    '',
    '# Save',
    'model.save_pretrained(OUTPUT_DIR)',
    'tokenizer.save_pretrained(OUTPUT_DIR)',
    `print(f"Model saved to {OUTPUT_DIR}")`,
  ].filter(l => l !== null && l !== undefined));
}

// ── Ternary BitNet ────────────────────────────────────────────────────

export function generateTernaryScript(config: {
  baseModel: string; outputDir: string; dataset: string; epochs: number;
  batchSize: number; learningRate: number; maxSeqLength: number;
  loraRank: number; seed: number; outputName: string;
}): string {
  return buildScript([
    '#!/usr/bin/env python3',
    '"""',
    `Tekton Ternary (1.58-bit) BitNet Training Script`,
    `Model: ${config.baseModel}`,
    'Generated by Tekton ML-Ops',
    '"""',
    '',
    'import torch',
    'import torch.nn as nn',
    'from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments',
    'from trl import SFTTrainer',
    'from datasets import load_dataset',
    'from peft import LoraConfig, get_peft_model',
    '',
    'class TernaryWeightQuantizer(nn.Module):',
    '    """Quantize weights to {-1, 0, +1} (1.58-bit representation)."""',
    '    def quantize(self, weight):',
    '        scale = weight.abs().mean(dim=-1, keepdim=True)',
    '        centered = weight / (scale + 1e-8)',
    '        quantized = torch.where(centered > 0.5, torch.ones_like(centered),',
    '            torch.where(centered < -0.5, -torch.ones_like(centered), torch.zeros_like(centered)))',
    '        return quantized * scale',
    '',
    `MODEL_NAME = "${config.baseModel}"`,
    `OUTPUT_DIR = "${config.outputDir}/${config.outputName}"`,
    `DATASET = "${config.dataset}"`,
    `SEED = ${config.seed}`,
    '',
    'tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)',
    'model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.float16, device_map="auto")',
    '',
    `lora_config = LoraConfig(r=${config.loraRank}, lora_alpha=16, lora_dropout=0.05,`,
    '    target_modules=["q_proj", "v_proj"], task_type="CAUSAL_LM")',
    'model = get_peft_model(model, lora_config)',
    '',
    'dataset = load_dataset(DATASET, split="train")',
    `trainer = SFTTrainer(model=model, tokenizer=tokenizer, train_dataset=dataset,`,
    `    dataset_text_field="text", max_seq_length=${config.maxSeqLength},`,
    `    args=TrainingArguments(output_dir=OUTPUT_DIR, num_train_epochs=${config.epochs},`,
    `    per_device_train_batch_size=${config.batchSize}, learning_rate=${config.learningRate},`,
    '    fp16=True, logging_steps=10, save_steps=500, save_total_limit=3, seed=SEED))',
    '',
    'trainer.train()',
    'model.save_pretrained(OUTPUT_DIR)',
    'tokenizer.save_pretrained(OUTPUT_DIR)',
    `print(f"Ternary model saved to {OUTPUT_DIR}")`,
  ]);
}

// ── GRPO Reasoning ──────────────────────────────────────────────────

export function generateGRPOScript(config: {
  baseModel: string; outputDir: string; dataset: string; epochs: number;
  batchSize: number; learningRate: number; maxSeqLength: number;
  grpoBeta: number; rewardModel: string; seed: number; outputName: string;
}): string {
  const hasReward = config.rewardModel && config.rewardModel.length > 0;
  return buildScript([
    '#!/usr/bin/env python3',
    '"""',
    `Tekton GRPO Training Script`,
    `Model: ${config.baseModel}`,
    `Reward Model: ${hasReward ? config.rewardModel : "self-reward"}`,
    'Generated by Tekton ML-Ops',
    '"""',
    '',
    'import torch',
    'from transformers import AutoModelForCausalLM, AutoTokenizer',
    'from trl import GRPOConfig, GRPOTrainer',
    'from datasets import load_dataset',
    '',
    `MODEL_NAME = "${config.baseModel}"`,
    `OUTPUT_DIR = "${config.outputDir}/${config.outputName}"`,
    `DATASET = "${config.dataset}"`,
    `MAX_SEQ_LENGTH = ${config.maxSeqLength}`,
    `BETA = ${config.grpoBeta}`,
    `SEED = ${config.seed}`,
    '',
    'tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)',
    'model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.bfloat16, device_map="auto")',
    '',
    ...(hasReward ? [
      `REWARD_MODEL = "${config.rewardModel}"`,
      'reward_tokenizer = AutoTokenizer.from_pretrained(REWARD_MODEL)',
      'reward_model = AutoModelForCausalLM.from_pretrained(REWARD_MODEL, torch_dtype=torch.bfloat16, device_map="auto")',
      '',
      'def reward_fn(completions, prompts):',
      '    scores = []',
      '    for completion, prompt in zip(completions, prompts):',
      '        inputs = reward_tokenizer(prompt + completion, return_tensors="pt").to(reward_model.device)',
      '        with torch.no_grad():',
      '            output = reward_model(**inputs)',
      '        scores.append(output.logits[0, -1, :].max().item())',
      '    return scores',
    ] : [
      '# Self-reward: use generation quality as proxy',
      'def reward_fn(completions, prompts):',
      '    scores = []',
      '    for completion, prompt in zip(completions, prompts):',
      '        inputs = tokenizer(prompt + completion, return_tensors="pt").to(model.device)',
      '        with torch.no_grad():',
      '            output = model(**inputs, labels=inputs["input_ids"])',
      '        scores.append(-output.loss.item() / max(len(completion.split()), 1))',
      '    return scores',
    ]),
    '',
    'dataset = load_dataset(DATASET, split="train")',
    '',
    `grpo_config = GRPOConfig(output_dir=OUTPUT_DIR, num_train_epochs=${config.epochs},`,
    `    per_device_train_batch_size=${config.batchSize}, learning_rate=${config.learningRate},`,
    `    beta=BETA, max_completion_length=MAX_SEQ_LENGTH, seed=SEED,`,
    '    logging_steps=10, save_steps=500, bf16=True, report_to="none")',
    '',
    'trainer = GRPOTrainer(model=model, args=grpo_config, train_dataset=dataset,',
    '    reward_func=reward_fn, processing_class=tokenizer)',
    'trainer.train()',
    '',
    'model.save_pretrained(OUTPUT_DIR)',
    'tokenizer.save_pretrained(OUTPUT_DIR)',
    `print(f"GRPO model saved to {OUTPUT_DIR}")`,
  ]);
}

// ── Eval Harness ──────────────────────────────────────────────────────

export function generateEvalScript(config: {
  model: string; tasks: string[]; numShots: number; batchSize: number;
  maxSeqLength: number; outputDir: string;
}): string {
  const taskList = config.tasks.map(t => `"${t}"`).join(", ");
  return buildScript([
    '#!/usr/bin/env python3',
    '"""',
    `Tekton Evaluation Script`,
    `Model: ${config.model}`,
    `Benchmarks: ${config.tasks.join(", ")}`,
    'Generated by Tekton ML-Ops',
    '"""',
    '',
    'import json',
    'import os',
    '',
    'try:',
    '    from lm_eval import evaluator',
    '    LM_EVAL_AVAILABLE = True',
    'except ImportError:',
    '    LM_EVAL_AVAILABLE = False',
    '    print("WARNING: lm-eval not installed. pip install lm-evaluation-harness")',
    '',
    `MODEL_NAME = "${config.model}"`,
    `TASKS = [${taskList}]`,
    `NUM_FEWSHOT = ${config.numShots}`,
    `BATCH_SIZE = ${config.batchSize}`,
    `MAX_SEQ_LENGTH = ${config.maxSeqLength}`,
    `OUTPUT_DIR = "${config.outputDir}"`,
    '',
    'os.makedirs(OUTPUT_DIR, exist_ok=True)',
    '',
    'if LM_EVAL_AVAILABLE:',
    '    results = evaluator.simple_evaluate(',
    '        model="hf",',
    '        model_args=f"pretrained={MODEL_NAME}",',
    '        tasks=TASKS,',
    `        num_fewshot=${config.numShots},`,
    `        batch_size=${config.batchSize},`,
    '        device="auto",',
    '    )',
    '',
    '    scores = {}',
    '    for task_name, task_results in results.get("results", {}).items():',
    '        if isinstance(task_results, dict):',
    '            for metric_name, metric_value in task_results.items():',
    '                if "acc" in metric_name.lower():',
    '                    scores[task_name] = metric_value',
    '                    break',
    '',
    '    overall = sum(scores.values()) / len(scores) if scores else 0.0',
    '',
    '    output = {"model": MODEL_NAME, "tasks": TASKS, "scores": scores, "overall": overall}',
    '    with open(os.path.join(OUTPUT_DIR, "eval_results.json"), "w") as f:',
    '        json.dump(output, f, indent=2)',
    '    print(f"Results: {json.dumps(scores, indent=2)}")',
    '    print(f"Overall: {overall:.4f}")',
    'else:',
    '    print("lm-eval not available. Install with: pip install lm-evaluation-harness")',
  ]);
}