/**
 * ML-Ops Types — Training orchestration, GPU monitoring, dataset pipeline, evaluation.
 */
import { Static } from "@sinclair/typebox";
export declare const GPUInfoSchema: import("@sinclair/typebox").TObject<{
    detected: import("@sinclair/typebox").TBoolean;
    name: import("@sinclair/typebox").TString;
    vramTotalMB: import("@sinclair/typebox").TNumber;
    vramUsedMB: import("@sinclair/typebox").TNumber;
    vramFreeMB: import("@sinclair/typebox").TNumber;
    utilization: import("@sinclair/typebox").TNumber;
    driver: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    cuda: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type GPUInfo = Static<typeof GPUInfoSchema>;
export declare const EnvInfoSchema: import("@sinclair/typebox").TObject<{
    platform: import("@sinclair/typebox").TString;
    pythonAvailable: import("@sinclair/typebox").TBoolean;
    pythonVersion: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    nvidiaSmiAvailable: import("@sinclair/typebox").TBoolean;
    gpus: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        detected: import("@sinclair/typebox").TBoolean;
        name: import("@sinclair/typebox").TString;
        vramTotalMB: import("@sinclair/typebox").TNumber;
        vramUsedMB: import("@sinclair/typebox").TNumber;
        vramFreeMB: import("@sinclair/typebox").TNumber;
        utilization: import("@sinclair/typebox").TNumber;
        driver: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        cuda: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>>;
    cudaVersion: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    vramTotalMB: import("@sinclair/typebox").TNumber;
}>;
export type EnvInfo = Static<typeof EnvInfoSchema>;
export declare const TrainingMethod: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"qlora">, import("@sinclair/typebox").TLiteral<"ternary-bitnet">, import("@sinclair/typebox").TLiteral<"grpo">, import("@sinclair/typebox").TLiteral<"full-finetune">, import("@sinclair/typebox").TLiteral<"lora">]>;
export type TrainingMethod = Static<typeof TrainingMethod>;
export declare const PrecisionSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"fp16">, import("@sinclair/typebox").TLiteral<"bf16">, import("@sinclair/typebox").TLiteral<"fp32">, import("@sinclair/typebox").TLiteral<"8bit">, import("@sinclair/typebox").TLiteral<"4bit">]>;
export type Precision = Static<typeof PrecisionSchema>;
export declare const TrainingConfigSchema: import("@sinclair/typebox").TObject<{
    method: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"qlora">, import("@sinclair/typebox").TLiteral<"ternary-bitnet">, import("@sinclair/typebox").TLiteral<"grpo">, import("@sinclair/typebox").TLiteral<"full-finetune">, import("@sinclair/typebox").TLiteral<"lora">]>;
    baseModel: import("@sinclair/typebox").TString;
    outputName: import("@sinclair/typebox").TString;
    outputDir: import("@sinclair/typebox").TString;
    dataset: import("@sinclair/typebox").TString;
    datasetSplit: import("@sinclair/typebox").TString;
    epochs: import("@sinclair/typebox").TNumber;
    batchSize: import("@sinclair/typebox").TNumber;
    gradientAccumulationSteps: import("@sinclair/typebox").TNumber;
    learningRate: import("@sinclair/typebox").TNumber;
    weightDecay: import("@sinclair/typebox").TNumber;
    warmupSteps: import("@sinclair/typebox").TNumber;
    maxSeqLength: import("@sinclair/typebox").TNumber;
    precision: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"fp16">, import("@sinclair/typebox").TLiteral<"bf16">, import("@sinclair/typebox").TLiteral<"fp32">, import("@sinclair/typebox").TLiteral<"8bit">, import("@sinclair/typebox").TLiteral<"4bit">]>;
    loraRank: import("@sinclair/typebox").TNumber;
    loraAlpha: import("@sinclair/typebox").TNumber;
    loraDropout: import("@sinclair/typebox").TNumber;
    grpoBeta: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    grpoRewardModel: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    saveSteps: import("@sinclair/typebox").TNumber;
    evalSteps: import("@sinclair/typebox").TNumber;
    loggingSteps: import("@sinclair/typebox").TNumber;
    useUnsloth: import("@sinclair/typebox").TBoolean;
    useFlashAttention: import("@sinclair/typebox").TBoolean;
    deepspeed: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    fsdp: import("@sinclair/typebox").TBoolean;
    resumeFromCheckpoint: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    gpuIds: import("@sinclair/typebox").TString;
    seed: import("@sinclair/typebox").TNumber;
}>;
export type TrainingConfig = Static<typeof TrainingConfigSchema>;
export declare const JobStatus: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"queued">, import("@sinclair/typebox").TLiteral<"preparing">, import("@sinclair/typebox").TLiteral<"running">, import("@sinclair/typebox").TLiteral<"evaluating">, import("@sinclair/typebox").TLiteral<"completed">, import("@sinclair/typebox").TLiteral<"failed">, import("@sinclair/typebox").TLiteral<"cancelled">]>;
export type JobStatus = Static<typeof JobStatus>;
export declare const TrainingJobSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    name: import("@sinclair/typebox").TString;
    method: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"qlora">, import("@sinclair/typebox").TLiteral<"ternary-bitnet">, import("@sinclair/typebox").TLiteral<"grpo">, import("@sinclair/typebox").TLiteral<"full-finetune">, import("@sinclair/typebox").TLiteral<"lora">]>;
    status: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"queued">, import("@sinclair/typebox").TLiteral<"preparing">, import("@sinclair/typebox").TLiteral<"running">, import("@sinclair/typebox").TLiteral<"evaluating">, import("@sinclair/typebox").TLiteral<"completed">, import("@sinclair/typebox").TLiteral<"failed">, import("@sinclair/typebox").TLiteral<"cancelled">]>;
    config: import("@sinclair/typebox").TObject<{
        method: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"qlora">, import("@sinclair/typebox").TLiteral<"ternary-bitnet">, import("@sinclair/typebox").TLiteral<"grpo">, import("@sinclair/typebox").TLiteral<"full-finetune">, import("@sinclair/typebox").TLiteral<"lora">]>;
        baseModel: import("@sinclair/typebox").TString;
        outputName: import("@sinclair/typebox").TString;
        outputDir: import("@sinclair/typebox").TString;
        dataset: import("@sinclair/typebox").TString;
        datasetSplit: import("@sinclair/typebox").TString;
        epochs: import("@sinclair/typebox").TNumber;
        batchSize: import("@sinclair/typebox").TNumber;
        gradientAccumulationSteps: import("@sinclair/typebox").TNumber;
        learningRate: import("@sinclair/typebox").TNumber;
        weightDecay: import("@sinclair/typebox").TNumber;
        warmupSteps: import("@sinclair/typebox").TNumber;
        maxSeqLength: import("@sinclair/typebox").TNumber;
        precision: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"fp16">, import("@sinclair/typebox").TLiteral<"bf16">, import("@sinclair/typebox").TLiteral<"fp32">, import("@sinclair/typebox").TLiteral<"8bit">, import("@sinclair/typebox").TLiteral<"4bit">]>;
        loraRank: import("@sinclair/typebox").TNumber;
        loraAlpha: import("@sinclair/typebox").TNumber;
        loraDropout: import("@sinclair/typebox").TNumber;
        grpoBeta: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        grpoRewardModel: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        saveSteps: import("@sinclair/typebox").TNumber;
        evalSteps: import("@sinclair/typebox").TNumber;
        loggingSteps: import("@sinclair/typebox").TNumber;
        useUnsloth: import("@sinclair/typebox").TBoolean;
        useFlashAttention: import("@sinclair/typebox").TBoolean;
        deepspeed: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        fsdp: import("@sinclair/typebox").TBoolean;
        resumeFromCheckpoint: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        gpuIds: import("@sinclair/typebox").TString;
        seed: import("@sinclair/typebox").TNumber;
    }>;
    progress: import("@sinclair/typebox").TNumber;
    currentStep: import("@sinclair/typebox").TNumber;
    totalSteps: import("@sinclair/typebox").TNumber;
    currentEpoch: import("@sinclair/typebox").TNumber;
    totalEpochs: import("@sinclair/typebox").TNumber;
    trainLoss: import("@sinclair/typebox").TNumber;
    evalLoss: import("@sinclair/typebox").TNumber;
    gpuUtil: import("@sinclair/typebox").TNumber;
    gpuVramUsedMB: import("@sinclair/typebox").TNumber;
    samplesPerSecond: import("@sinclair/typebox").TNumber;
    startTime: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    endTime: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    error: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    checkpointDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    logPath: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TrainingJob = Static<typeof TrainingJobSchema>;
export declare const CheckpointSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    jobId: import("@sinclair/typebox").TString;
    step: import("@sinclair/typebox").TNumber;
    epoch: import("@sinclair/typebox").TNumber;
    trainLoss: import("@sinclair/typebox").TNumber;
    evalLoss: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    path: import("@sinclair/typebox").TString;
    sizeMB: import("@sinclair/typebox").TNumber;
    timestamp: import("@sinclair/typebox").TNumber;
    isBest: import("@sinclair/typebox").TBoolean;
}>;
export type Checkpoint = Static<typeof CheckpointSchema>;
export declare const ExportFormat: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"gguf">, import("@sinclair/typebox").TLiteral<"safetensors">, import("@sinclair/typebox").TLiteral<"onnx">, import("@sinclair/typebox").TLiteral<"mlx">]>;
export type ExportFormat = Static<typeof ExportFormat>;
export declare const DatasetFormatSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"alpaca">, import("@sinclair/typebox").TLiteral<"sharegpt">, import("@sinclair/typebox").TLiteral<"jsonl">, import("@sinclair/typebox").TLiteral<"parquet">, import("@sinclair/typebox").TLiteral<"csv">, import("@sinclair/typebox").TLiteral<"huggingface">]>;
export type DatasetFormat = Static<typeof DatasetFormatSchema>;
export declare const DatasetConfigSchema: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    source: import("@sinclair/typebox").TString;
    format: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"alpaca">, import("@sinclair/typebox").TLiteral<"sharegpt">, import("@sinclair/typebox").TLiteral<"jsonl">, import("@sinclair/typebox").TLiteral<"parquet">, import("@sinclair/typebox").TLiteral<"csv">, import("@sinclair/typebox").TLiteral<"huggingface">]>;
    split: import("@sinclair/typebox").TString;
    tokenizer: import("@sinclair/typebox").TString;
    maxSeqLength: import("@sinclair/typebox").TNumber;
    shuffleSeed: import("@sinclair/typebox").TNumber;
    trainSplitRatio: import("@sinclair/typebox").TNumber;
}>;
export type DatasetConfig = Static<typeof DatasetConfigSchema>;
export declare const DatasetInfoSchema: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    numSamples: import("@sinclair/typebox").TNumber;
    numTokens: import("@sinclair/typebox").TNumber;
    avgSeqLength: import("@sinclair/typebox").TNumber;
    trainSamples: import("@sinclair/typebox").TNumber;
    valSamples: import("@sinclair/typebox").TNumber;
    shards: import("@sinclair/typebox").TNumber;
    path: import("@sinclair/typebox").TString;
}>;
export type DatasetInfo = Static<typeof DatasetInfoSchema>;
export declare const MetricPointSchema: import("@sinclair/typebox").TObject<{
    step: import("@sinclair/typebox").TNumber;
    epoch: import("@sinclair/typebox").TNumber;
    trainLoss: import("@sinclair/typebox").TNumber;
    evalLoss: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    learningRate: import("@sinclair/typebox").TNumber;
    gpuUtil: import("@sinclair/typebox").TNumber;
    gpuVramMB: import("@sinclair/typebox").TNumber;
    samplesPerSecond: import("@sinclair/typebox").TNumber;
    timestamp: import("@sinclair/typebox").TNumber;
}>;
export type MetricPoint = Static<typeof MetricPointSchema>;
export declare const EvalResultSchema: import("@sinclair/typebox").TObject<{
    benchmark: import("@sinclair/typebox").TString;
    scores: import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TNumber>;
    overall: import("@sinclair/typebox").TNumber;
    timestamp: import("@sinclair/typebox").TNumber;
}>;
export type EvalResult = Static<typeof EvalResultSchema>;
export declare const TrainingRequestSchema: import("@sinclair/typebox").TObject<{
    method: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"qlora">, import("@sinclair/typebox").TLiteral<"ternary-bitnet">, import("@sinclair/typebox").TLiteral<"grpo">, import("@sinclair/typebox").TLiteral<"full-finetune">, import("@sinclair/typebox").TLiteral<"lora">]>;
    baseModel: import("@sinclair/typebox").TString;
    dataset: import("@sinclair/typebox").TString;
    outputName: import("@sinclair/typebox").TString;
    options: import("@sinclair/typebox").TObject<{
        method: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"qlora">, import("@sinclair/typebox").TLiteral<"ternary-bitnet">, import("@sinclair/typebox").TLiteral<"grpo">, import("@sinclair/typebox").TLiteral<"full-finetune">, import("@sinclair/typebox").TLiteral<"lora">]>>;
        baseModel: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        outputName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        outputDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataset: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        datasetSplit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        epochs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        batchSize: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        gradientAccumulationSteps: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        learningRate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        weightDecay: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        warmupSteps: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxSeqLength: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        precision: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"fp16">, import("@sinclair/typebox").TLiteral<"bf16">, import("@sinclair/typebox").TLiteral<"fp32">, import("@sinclair/typebox").TLiteral<"8bit">, import("@sinclair/typebox").TLiteral<"4bit">]>>;
        loraRank: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        loraAlpha: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        loraDropout: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        grpoBeta: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        grpoRewardModel: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        saveSteps: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        evalSteps: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        loggingSteps: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        useUnsloth: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        useFlashAttention: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        deepspeed: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        fsdp: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        resumeFromCheckpoint: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        gpuIds: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        seed: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    }>;
}>;
export type TrainingRequest = Static<typeof TrainingRequestSchema>;
export declare const OrchestratorStateSchema: import("@sinclair/typebox").TObject<{
    initialized: import("@sinclair/typebox").TBoolean;
    envInfo: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        platform: import("@sinclair/typebox").TString;
        pythonAvailable: import("@sinclair/typebox").TBoolean;
        pythonVersion: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        nvidiaSmiAvailable: import("@sinclair/typebox").TBoolean;
        gpus: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
            detected: import("@sinclair/typebox").TBoolean;
            name: import("@sinclair/typebox").TString;
            vramTotalMB: import("@sinclair/typebox").TNumber;
            vramUsedMB: import("@sinclair/typebox").TNumber;
            vramFreeMB: import("@sinclair/typebox").TNumber;
            utilization: import("@sinclair/typebox").TNumber;
            driver: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            cuda: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        }>>;
        cudaVersion: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        vramTotalMB: import("@sinclair/typebox").TNumber;
    }>>;
    activeJobs: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>;
    completedJobs: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>;
    totalGpuHours: import("@sinclair/typebox").TNumber;
}>;
export type OrchestratorState = Static<typeof OrchestratorStateSchema>;
export declare const DEFAULT_TRAINING_CONFIG: TrainingConfig;
//# sourceMappingURL=types.d.ts.map